name: Deploy to shared hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to shared hosting
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.example.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        remote-dir: /public_html/oluwafemi.name.ng
